dataset:
  books_csv: "./backend_files/data/books_data/books.csv"
  ratings_csv: "./backend_files/data/books_data/ratings.csv"
  users_csv: "./backend_files/data/books_data/users.csv"

llm_models:
  selected_llm: "openai"
  available_llms: ["openai","groq","ollama"]
  openai:
    base_url : 'https://api.openai.com/v1/'
    model_name: 'gpt-3.5-turbo'
    api_key_name: 'OPENAI_API_KEY'
    temperature: 0.0
  
  groq:
    base_url : 'https://api.groq.com/openai/v1'
    model_name: 'Llama3-70B-8192'
    api_key_name: 'GROQ_API_KEY'
    temperature: 0.0

  ollama:
    model_name: "llama3:instruct"
    temperature: 0.0

rag:
  chat_memory:
    window_buffer: 6

  vectorstore:
    embedding_model: "all-MiniLM-L6-v2"
    vectordb_cache_directory: "DB_files/vectorDB_caches/db_01"
    dataloader:
      csv_loader:
        splitter:
          seperator: "\n"
          chunk_size: 450
          chunk_overlap: 0
        encoding: "windows-1252"
        metadata_columns : ["ISBN", "Image-URL-S", "Image-URL-M", "Image-URL-L"]

    retriever:
      conversation_buffer_window_size: 4
      retriver_k: 200
      semantic_search_score_threshold: 0.3
      search_type: "similarity"
      metadata_columns: ["ISBN", "Image-URL-S", "Image-URL-M", "Image-URL-L"]

  prompt:
    main_search:
      system_prompt: "utils/prompt_templates/main_semantic_search/system_prompt.txt"
      user_prompt: "utils/prompt_templates/main_semantic_search/system_prompt.txt"

  mongodb:
    mongodb_host: "mongodb://localhost:27017/"
    max_mongodb_results: 10
    mongodb_collection_name : "book-database"
    mongodb_database_name : "book_recomending_database_1"

